name: Generate snake animation

on:
  schedule: # execute daily
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-snake.svg
                   dist/github-snake-dark.svg?palette=github-dark
        env:
          TOKEN: ${{ secrets.GH_PAT }}

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          TOKEN: ${{ secrets.GH_PAT }}
